version: '3.8'

services:
  inove-frontend:
    build: .
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
    depends_on:
      - inove-backend